### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by morozgrafix** [chetan/simplecov-console#11]
Just wanted to check if this Gem is still maintained and updated? I've attempted to use it and noticed that some of the dependencies are fairly obsolete. Wanted to check before attempting to get a working fork or if this gem is abandoned creating a new one based on this.

Thanks.

**Comment by chetan** [comment]
It's not being actively developed (or used by me at the moment), but I do try to review and merge PRs as they come up. Which dependencies in particular are you having problems with?

**Comment by morozgrafix** [comment]
Thanks for responding. looks like [hirb](https://github.com/cldwalker/hirb) (which possibly isn't well maintained) produces warnings that trickle down to reports. Some details are here https://github.com/cldwalker/hirb/issues/103 (there is an open [PR](https://github.com/cldwalker/hirb/pull/104) to fix that but it has been open for about 10 months without any activity)

The reason why I checked is that I was thinking about using another table generating gem for the output and wanted to check with you if this repo is still active before starting to implement it.

**Comment by chetan** [comment]
Gotcha. I'm happy to merge if you open the PR. Should be easy enough to swap out for another library.

**Comment by chetan** [comment]
Had some time so I went ahead and implemented this using terminal-table. v0.5 is up on rubygems now. Let me know if you see any issues still.

**Comment by morozgrafix** [comment]
Thanks for updating it.
