### ISSUE TITLE
disable output when running against a single file?

### ISSUE THREAD

**Issue by tansaku** [chetan/simplecov-console#14]
Love this gem!

Just wondering it it would make sense to disable the output when running against a single spec?

**Comment by chetan** [comment]
Wouldn't the coverage report still include multiple touched files though?

**Comment by tansaku** [comment]
there are a couple of different circumstances.   At the moment when I am focused on trying to get a single test to pass the output that I get from simplecov-console kind of gets in the way as it's quite long and is showing me coverage for files that **seem** unrelated to the single test that I'm trying to get to pass.  So to deal with this then I comment out the following in spec_helper.rb

```rb
SimpleCov.formatter = SimpleCov::Formatter::Console
```
that allows me to focus on the individual error and get that fixed.

Then there's the situation when I'm trying to work out what kind of coverage I'm getting on a single file and I have rspec focused on running a single test file that is supposed to fully exercise a single file of code, e.g. only running `foo_spec.rb` to exercise `foo.rb`, and in this case I'd love to see the coverage, similarly when I'm running the full test suite after I've gotten things working.

I guess the thing is there are times where I want to see the coverage information and times when I don't.  When I have the test focus on `Run options: include {:focus=>true}` I think I pretty much don't want to see the coverage.  Was just thinking about auto-disabling in the spec-folder ... but I guess I don't have information about whether the focus is true at the point at which I'm setting the formatter.

I guess what I want is something like this in the spec_helper:

```rb
RSpec.after(:suite) do
  SimpleCov.formatter = SimpleCov::Formatter::Console unless RSpec.configuation.focus
end
```

so that I can avoid commenting and uncommenting the coverage formatter in spec_helper as I'm working, but the above doesn't work as it needs to be associated with a test suite - so not sure how to do this globally.  Am I making any sense? :-)

**Comment by chetan** [comment]
Gotcha, I can see that being useful. I think perhaps you can do this directly in your helper setup, though.  I'm not super familiar with rspec, but with minitest, the following is possible:

ref: https://github.com/chetan/simplecov-console-test/blob/master/test/helper.rb#L8-L10

```ruby
SimpleCov.start do
  formatters = [SimpleCov::Formatter::HTMLFormatter]
  formatters << SimpleCov::Formatter::Console if ENV["TEST"].nil?
  SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new(formatters)
end
```

It may vary a bit depending on how you're running the single test, but it seems like a simple workaround. 

Alternatively, perhaps exposing an ENV/rake flag to disable it from the CLI would be more preferable? In which case, a pull request would be happily welcomed.

**Comment by tansaku** [comment]
yeah, disabling from the CLI could be a good option ... in the example you give I guess that's switching it off completely in test mode ... I might open a ticket on rspec to ask them about detecting the focus ...

**Comment by tansaku** [comment]
in the first instance I've gone with:

```
SimpleCov.formatter = SimpleCov.formatter = SimpleCov::Formatter::Console if ENV['SIMPLECOV_CONSOLE']
```

and then I can run:

```
SIMPLECOV_CONSOLE=true bundle exec rspec
```
but we'll see if the rspec folks can't suggest a better way, as the danger with the env var approach is that one never remembers to look at the detailed coverage output again

also I'd really like a way to restrict a focused coverage report to the touched files, but that's another story ...

**Comment by tansaku** [comment]
woohoo, and the rspec folks have come through with a solution:

```rb
SimpleCov.formatter = SimpleCov::Formatter::Console
RSpec.configuration.when_first_matching_example_defined(focus: true) do
  SimpleCov.formatter = SimpleCov::Formatter::SimpleFormatter
end
```

**Comment by chetan** [comment]
👍
