### ISSUE TITLE
Cannot load ./output/table for default table output

### ISSUE THREAD

**Issue by glangloi** [chetan/simplecov-console#17]
https://github.com/chetan/simplecov-console/blob/b2d3598d310d4fdc916de69c1a4bef94d555502f/lib/simplecov-console.rb#L35

This require statement can't find the correct file. I think it needs to be changed to:

```ruby
require 'simplecov-console/output/table'
```

**Comment by chetan** [comment]
Ugh, my mistake. Missed a commit when pushing the previous. Fixed now in 0.7.2.
