### ISSUE TITLE
Branch coverage support

### ISSUE THREAD

**Issue by rmacklin** [chetan/simplecov-console#18]
`simplecov` supports measuring branch coverage in addition to line coverage:
https://github.com/simplecov-ruby/simplecov/tree/818bc2547842a90c607b4fec834320766a8686de#branch-coverage-ruby--25

It seems like this formatter currently displays line coverage results but not branch coverage results. Would it be valuable to explicitly mention this in the README? Or, have you thought about supporting branch coverage?

**Comment by chetan** [comment]
@rmacklin just pushed v0.8 with branch support. Let me know if you see any issues
