### ISSUE TITLE
Table too wide, not truncating with ellipse

### ISSUE THREAD

**Issue by lbraun** [chetan/simplecov-console#20]
We are adding simplecov-console to a project with very poor coverage. The output has so many entries in the "missing" column that every row wraps and is rather unreadable. The README implies that the content of that column should be truncated with an ellipse, if there are too many missing lines.

Is this a configuration that I am not finding? Thanks for your help.

**Comment by chetan** [comment]
@lbraun tbh, I think I may have manually added an ellipse for the purposes of the readme as the output was too long to display nicely. I should probably update that with a more recent example from my test repo. 

That said, it's an easy enough change to add this sort of limit. Wil be pushing a change to do that shortly.

**Comment by chetan** [comment]
Fixed in v0.9

**Comment by lbraun** [comment]
Thanks so much @chetan ! 
Works great. 

I made one small improvement in https://github.com/chetan/simplecov-console/pull/21
