### ISSUE TITLE
Bump version and update RubyGems if possible

### ISSUE THREAD

**Issue by mentero** [chetan/simplecov-console#4]
Hi!

I love this gem but fetching it from RubyGems gives a 0.2.0 version without a latest patch (#3). 
And it looks like the RubyGems one is no longer valid resulting with
```ruby
Formatter SimpleCov::Formatter::Console failed with TypeError: no implicit conversion of Symbol into String (/<removed>/gems/colored-1.2/lib/colored.rb:70:in `colorize')
```

I moved to the master with 
```ruby
gem 'simplecov-console', github: 'chetan/simplecov-console'
```
and now everything seems to work ok.

So if there is a possibility please update gem version and publish it to RubyGems.

Thanks a lot :)

**Comment by chetan** [comment]
Thanks for the reminder, just pushed v0.3 to rubygems.
