### ISSUE TITLE
Console formatter calculates root path incorrectly, and there's no clean way to change it

### ISSUE THREAD

**Issue by dmolesUC3** [chetan/simplecov-console#5]
I have a somewhat oddball project that pulls in some Rails engines as gems without actually being a Rails application. When I run the tests under Simplecov, the console formatter is producing output of the form:

```
| 90.91% | Usersmynameproject-dirlibmodule... | 11 | 1 | 15                 |
```

Running the rake task in the debugger, it seems as though the problem is in how `Simplecov::Formatter::Console` [calculates the root path](https://github.com/chetan/simplecov-console/blob/v0.3.0/lib/simplecov-console.rb#L10-L19) used for simplifying filenames in the output.

Because my project isn't actually a Rails app, but has the `Rails` constant defined, `Simplecov::Formatter::Console` tries to use `Rails.root`, which is `nil`, and ends up stripping all `/` from the filenames.

From the source, it seems as though I should be able to use the `:ROOT` constant to set the root path used for simplifying filenames in the console output. However, this doesn't work.

If I set `Simplecov::Formatter::Console::ROOT = Dir.pwd` in my `spec_helper.rb`, `Module.const_defined? :ROOT` returns false, and it's ignored.

If I set `Module::ROOT = Dir.pwd`, `Module.const_defined?` returns true, but `Simplecov::Formatter::Console::ROOT` is undefined, and I get `NameError: uninitialized constant`.

I can work around this by setting both constants, but I don't think this is what the code intends.

**Comment by chetan** [comment]
What about implementing `Rails.root` to return the correct path, since you have that defined? Is that an option for you?

**Comment by chetan** [comment]
I think that should do it either way. Just pushed 0.3.1. Let me know if you still have trouble.

**Comment by dmolesUC3** [comment]
I think that'll fix it, but I still don't think `Module.const_defined?` is doing what you meant it to.

**Comment by chetan** [comment]
Yeah, you're probably right about that. I'm not actively using this now, so don't want to break any other existing stuff.
